Heading from imu take2
thingswebuilt/osod24_firmware pull request #28
Opened 2024-01-04 21:30 UTC by markmellors

BNO080 library added, and used in state_estimator to provide the heading for the robot's state and the odometry. Works on a naked motor2040 board with BNO080 connected via qwiic cable. currently untested on the robot chassis, so this is just for review purposes for now, until I can solder the headers. .

2024-01-13 09:41 UTC, robberwick commented
marking as draft until headers are soldered 😄

2024-01-14 22:12 UTC, markmellors commented
rebased and refactored to fit with the new structure of state_estimator. Tested and seems to work. Odometry drifts less than 10% per distance travelled (better than Tauradigm), need to do some better tests once the PID is better tuned.
Ready for review

2024-02-04 13:26 UTC, markmellors commented
Are we waiting on something before this can be merged into main? As far as I know, it's ready to go.

2024-02-04 15:48 UTC, robberwick commented
I thought it was gated on this:

>  so this is just for review purposes for now, until I can solder the headers. .

I had deferred review until that had changed, and the code had been tested on the prototype hardware. If that's happened, I'll take a proper look :+1:

2024-02-04 16:07 UTC, markmellors commented
Yeah, that status changed with this update: https://github.com/thingswebuilt/osod24_firmware/pull/28#issuecomment-1891088130

2024-02-04 16:23 UTC, robberwick commented
Then I'll take a proper look :eyes:

2024-02-10 10:23 UTC, robberwick requested changes
kudos on the porting 👍 

the branch looks to be a bit out of date with main (that pico-cppm submodule is no longer needed), so a rebase on current main might be in order.

also, i think we should probably not be initialising the IMU directly in the StateEstimator, but passing in a pointer to a BNO object and doing all the setup elsewhere - maybe even in `main()`?

2024-02-10 10:23 UTC, robberwick commented on libs/config/include/drivetrain_config.h
> +    constexpr int I2C_SDA_PIN = 20;
perhaps we should split this `drivetrain_config.h` file up into separate concerns - physical bot dimensions that are used to calculate wheel speeds, turn rates etc, and electrical properties e.g. pin mappings etc. what do you think?

2024-02-10 10:23 UTC, robberwick commented on include/pico-cppm
we no longer include `pico-cppm` as a submodule directly - it's pulled in via cmake's `FetchContent` in the `receiver` `CmakeLists.txt`. Perhaps this branch needs rebasing on latest `main`.

2024-02-10 10:23 UTC, robberwick commented on libs/bno080/include/bno080.h
> +  This is a library written for the BNO08x
we should probably go through and tweak all the comments herein to reflect the fact that it's no longer arduino, and you did some porting work to use it on the RP2040. But that's only if we're being super fastidious. otherwise 🤷

2024-02-10 10:23 UTC, robberwick commented on libs/common/CMakeLists.txt
> +target_include_directories(common PUBLIC
why did you have to make this change?

2024-02-10 10:23 UTC, robberwick commented on libs/state_estimator/src/state_estimator.cpp
> +    StateEstimator::StateEstimator(i2c_inst_t* port) : encoders{
I think the state estimator is responsible for a bit too much here. The creation and management of the BNO instance is outside of the scope of the StateEstimator. I think that rather than passing in an i2c port we should be passing in a pointer to an instance of the BNO080 object, and using that  to perform the state estimation functions. T

2024-02-10 16:17 UTC, markmellors commented on libs/config/include/drivetrain_config.h
> +    constexpr int I2C_SDA_PIN = 20;
agree, that's issue #21 . do you think this PR is the place to address it?

2024-02-10 16:17 UTC, markmellors commented on include/pico-cppm
removed

2024-02-10 16:40 UTC, markmellors commented on libs/common/CMakeLists.txt
> +target_include_directories(common PUBLIC
¯\_(ツ)_/¯   to keep CMAKE happy

2024-02-10 21:54 UTC, markmellors commented
I think its ready for another review

2024-02-24 12:10 UTC, robberwick commented
> I think its ready for another review

sorry i missed this - it didn't show up in my 'awaiting review' list. If you click the little icon up there next to my name under reviewers, it'll request another review:

<img width="238" alt="image" src="https://github.com/thingswebuilt/osod24_firmware/assets/1022090/9bfd0a4d-d070-41eb-abd5-408e5a53c48c">

2024-02-24 12:14 UTC, robberwick commented on src/main.cpp
> +        printf("Could not enable rotation vector\n");
do we need to know this? what do we do if we can't enable the rotation vector?

2024-02-25 09:04 UTC, robberwick commented on libs/config/include/drivetrain_config.h
> +    constexpr int I2C_SDA_PIN = 20;
probably not actually - this pr already has a fair amount of churn

2024-03-03 11:49 UTC, robberwick approved these changes
LGTM :+1:

2024-03-03 11:49 UTC, merged