Reading the Balance port (if present)
thingswebuilt/osod24_firmware pull request #49
Opened 2024-02-19 23:15 UTC by markmellors

seems to work well. gives a useful message if there's a problem. Currently the program doesn't change behaviour if there's a problem though.

2024-02-24 12:03 UTC, robberwick requested changes
looks good. I think it's worth extracting the `ADS1x15` library out into it's own thing, and ther are a couple of other very minor comments

2024-02-26 22:50 UTC, markmellors commented on libs/balance_port/include/balance_port.h
> +#include "ads1x15.h"
`ADS1x15` is now a seperate (external) library, but the `balance_port` library is still tightly coupled to it.

2024-02-26 23:01 UTC, markmellors commented on libs/receiver/src/receiverCPPM.cpp
> +    return decoder->getFrameAgeUs() > 0;
no, but it was needed to get my code to compile. This change is now on `main`. I'd cherrypicked the commit from  #48 , so expected this change to disappear with a rebase. I've now rebased, but it's made it worse, we now appear to have two commits making this change! I'm confused.

2024-03-10 20:39 UTC, robberwick approved these changes
Yes :+1:

2024-03-10 20:40 UTC, merged