Allow us to set which end of the robot is considered the front
thingswebuilt/osod24_firmware pull request #53
Opened 2024-03-07 20:03 UTC by markmellors

This allows us to drive "backwards" (steereable wheels at the back) for the Ecodisaster challenge, without any other changes.

2024-03-09 22:18 UTC, markmellors commented
I think its worth thinking about if I've made this flip in the best place. I was hoping it would only require a change in the navigator, then everything onwards in the chain would be the same. So, as coded in this PR, a request to go forward is received in the navigator, it could flip that to reverse if we're considering the back as the front, then the statemanager makes the robot to go in reverse. Unfortunately odometry (state_estimator) also needs to know the direction, either by offsetting the heading 180 degrees somewhere, or in how the X & Y estimates are updated. 
I think theres probably an alternative implementation where the navigator is the same for which ever direction we're going, and its the state_manager that changes. I'm not sure what would happen in that case with state_esitmator. maybe it would still need to change. 
I did it this way in case there's a dynamics difference between chassis forwards and chassis backwards, but I haven't thought the options through in that much detail.

2024-03-10 12:04 UTC, robberwick requested changes
Looks ok - I think i'd simplify the driving direction enum thiing a little (see comments).

In terms of broader implementation approaches, this seems fine to me - it's certainly good enough to go with until we encounter any issues :+1:.

2024-03-10 12:04 UTC, robberwick commented on libs/state_estimator/src/state_estimator.cpp
> +        if (direction == CONFIG::DrivingDirection::SteerableWheelsAtFront){
again, we could just use the `DriveDirection` enum alue directly here, if we set the values (see above)

2024-03-10 12:47 UTC, markmellors commented on libs/config/include/drivetrain_config.h
> +        constexpr float WHEEL_DIAMETER = SMALL_WHEEL_DIAMETER; //LARGE_WHEEL_DIAMETER;
That would be less verbose, but I think I prefer the exhaustive list approach, it makes it clearer to me in this case. I think we'd still need the If..elif..else as there are that many different configurations.

2024-03-10 14:51 UTC, robberwick commented on libs/config/include/drivetrain_config.h
> +        SteerableWheelsAtFront,
`Car` and `Forklift` are improvements, but they're not `DrivingDirections`

```suggestion

    enum SteeringStyle {
        CAR = 1,
        FORKLIFT = -1
    };

```

2024-03-10 14:53 UTC, robberwick requested changes
close, but i'm a pedant. sorry.

2024-03-16 13:30 UTC, robberwick approved these changes
Excellent :+1:

2024-03-16 13:30 UTC, merged