Enable zeroing odometry (heading and X/Y) and assign them to transmitter channels
thingswebuilt/osod24_firmware pull request #54
Opened 2024-03-07 21:11 UTC by markmellors

The methods work, but I've had to add a sleep to stop them double-triggering before the values have propogated through the system, and effectively reverting what's just been set.
They work as they are and the time delay isn't currently a problem since we're setting them manually whilst stationary.  
I've added some notes about this, I wonder if it'd be better to add a timed lock to the functions to prevent the double triggering (so that other functions aren't blocked if we use the methods in autonomous mode whilst driving), or if there's a better way to zero/apply offsets that doesn't suffer from the double-triggering problem?
Hopefully the potential double triggering failure mode is fairly clear. For setOrigin, I think it's because it uses Navigator's current_state property which takes some time to be updated, so if you call it twice in row before the values have propogated, you first set the origin to zero, then the second time you offset it again, effectively to minus the previous values.

2024-03-08 21:59 UTC, markmellors commented
also addresses #35

2024-03-10 23:26 UTC, markmellors commented
I've made the changes we discussed (they seem to work well!), so ready for another / more detailed review

2024-03-16 10:04 UTC, robberwick requested changes
Looks good! just one small tweak i noticed with the `parseTXSignals` to improve preformance.. i know, it's probably a premature optimisation, but it's a tiny tweak, and almost certainly a cheap win.

Other than that :+1:

2024-03-16 15:58 UTC, robberwick approved these changes
LGTM (but it would be a surprise if it didn't, I guess... 😉 )

2024-03-16 15:58 UTC, robberwick commented
Has some conflicts to resolve, and then it's mergeable

2024-03-17 09:32 UTC, robberwick commented
to save me re-reviewing this again, i'm happy if it passed a manual test by trying out the build on the robot. if you want to do that and then hit the merge button when you're satisfied that it's working, that works for me 👍

2024-03-17 11:43 UTC, markmellors commented
tested, works

2024-03-17 11:44 UTC, merged