library to Read TOFs
thingswebuilt/osod24_firmware pull request #56
Opened 2024-03-09 22:40 UTC by markmellors

I think this is step one of two. This PR makes the ToF distances a property of `estimatedState`, but otherwise doesn't do anything with them.  I have added a new function `showValuesViaCSV()` in `state_estimator` that makes it easier to process the log data with timestamps, and that prints out the distance readings. Once this is in `main` I'll a optional/configurable function in `state_estimator` that uses the distances to estimate the X,Y location within a rectangular arena.

2024-03-10 14:22 UTC, robberwick requested changes

2024-03-10 14:22 UTC, robberwick commented on libs/state_estimator/src/state_estimator.cpp
> +        auto now = duration_cast<milliseconds>(system_clock::now().time_since_epoch()).count();
we could use the `millis` helper from Pimoroni if we're keeping this, which would mean we could drop the `chrono` include

2024-03-10 14:22 UTC, robberwick commented on libs/tf_luna/src/tf_luna.cpp
> +}
```suggestion
LidarData getLidarData(uint8_t i2c_addr, i2c_inst_t* i2c_port) {
    std::array<uint8_t, 9> temp = {0};
    i2c_write_blocking(i2c_port, i2c_addr, getLidarDataCmd, 5, false); // Send command
    i2c_read_blocking(i2c_port, i2c_addr, temp.data(), 9, false); // Read response

    LidarData data = {0, 0, 0}; // Initialize to zero

    auto [header1, header2, distLow, distHigh, strengthLow, strengthHigh, tempLow, tempHigh, _] = temp;
    
    if (header1 == 0x59 && header2 == 0x59) {
        data.distance = distLow + distHigh * 256; // Distance value
        data.strength = strengthLow + strengthHigh * 256; // Signal strength
        data.temperature = (tempLow + tempHigh * 256) / 8 - 256; // Chip temperature
    }

    return data;
}
```

2024-03-10 14:22 UTC, robberwick commented on libs/tf_luna/include/tf_luna.h
> +LidarData getLidarData(uint8_t i2c_addr, i2c_inst_t* i2c_port);
if we had a `getLidarDataAll`, we could pass in a struct of i2c addresses and return a  `tofDistances` struct, which might save on a bit of boilerplate

2024-03-10 14:28 UTC, robberwick requested changes
we should definitely make the change to use the Pimoroni provided `millis` wrapper around the pico SDK time functions. We probably also want to address the use case of 'read all the tofs and return me a struct with the distance values only" by introducing a `getLidarDataAll` (and renaming the existing one to `getLidarDataSingle` or something?)

2024-03-16 10:22 UTC, robberwick approved these changes
LGTM :+1:

2024-03-17 09:37 UTC, robberwick commented
I approved this yesterday, but i don't know why i didn't merge it.. maybe there were conflicts? Either way, if you're happy that the rebased build works ok on the robot with a bit of manual testing, that's good enough for me - go ahead and hit the Big Green Button :+1:

2024-03-17 12:38 UTC, markmellors commented
tested, works

2024-03-17 12:39 UTC, merged