Tof localisation
thingswebuilt/osod24_firmware pull request #57
Opened 2024-03-15 22:33 UTC by markmellors

This is the part 2 mentioned in  #56 . It adds the TOF based arena localisation (that was prototyped with the circuitPython test rig) to the state estimator. It's working well in the test arena, and matches the odometry well but eliminates all drift. It currently just uses a weighted average to combine odometry and the arena estimate, but in future it could be developed into a kalman filter.
It adds quite a lot of complexity to state_estimator, I think it could probably do with being refactored out (later?) into a seperate module.

2024-03-16 10:58 UTC, robberwick requested changes
looks ok - some minor comments around naming etc, but a more serious concern about the use of `vector` which needs thinking about at least.

2024-03-16 10:58 UTC, robberwick commented on libs/common/include/types.h
>          float x;
minor suggestion: a `Point` class with `x` and `y` properties might be generally useful elsewhere, so creating one of those and then replacing the `x` and `y` fields here with a `loc`/`location` field might save some refactoring later.

2024-03-16 10:58 UTC, robberwick commented on libs/state_estimator/include/state_estimator.h
> +                                                                    const vector<float>& yPositions);
minor: that is some _very_ weird formatting

2024-03-16 10:58 UTC, robberwick commented on libs/state_estimator/include/state_estimator.h
> +        pair<vector<float>, vector<float>> createPermutation(int permutation,
beware of the use of `vector` in embedded projects - it dynamically allocates memory on the heap which _might_ be a problem. if it's possible to avoid their use in favour of statically allocated fixed size arrays, that might be preferable.

2024-03-16 10:58 UTC, robberwick commented on libs/state_estimator/src/state_estimator.cpp
> +        for (int permutation = 1; permutation < 16; ++permutation) {
minor: this feels like a _bit_ of a magic number. suggest lifting up into a private var with a comment  or if it's ever likely to change, perhaps dynamically calculate it in the constructor?

2024-03-16 10:58 UTC, robberwick commented on libs/state_estimator/src/state_estimator.cpp
> +            }
suggest extracting this out into a `generatePermutations` method or similar.

2024-03-16 10:58 UTC, robberwick commented on libs/tf_luna/src/tf_luna.cpp
> +    float front_m = static_cast<float>(front_mm) / 100.0f + CONFIG::TOF_FRONT_OFFSET;
suggest breaking this repeated operation out into a helper function

2024-03-16 10:58 UTC, robberwick commented on libs/state_estimator/include/state_estimator.h
> +        explicit StateEstimator(BNO08x* IMUinstance, i2c_inst_t* port, float arenaDimension);
does this need to take `arenaDimension` as a constructor param? Can it not pull it from the already imported `drivetrain_config`?

2024-03-16 10:58 UTC, robberwick commented on libs/state_estimator/include/state_estimator.h
> +        tuple<float, float, float> coordinateVariance(const vector<float>& xList, const vector<float>& yList);
minor/naming: a good rule of thumb is to name methods as verbs, rather than adjective/noun pairs. suggest `calculatePossiblePositions` and `calculateCoordinateVariance` or similar

2024-03-16 17:07 UTC, markmellors commented on libs/common/include/types.h
>          float x;
agree, I did wonder about that. We have a Point class in #50 , I wasn't sure if I should reproduce/cherry pick that, or if that PR would be finished before this one, so we'd get it (and use it) when when the rebase happens. 
Related, I'm nto sure if TOF localisation should only concern itself with the position, or if (in future) it can infer/improve the heading estimate. At the moment it does nothing with the heading so a point output makes more sense right now.

2024-03-17 10:18 UTC, robberwick approved these changes
Looks good - only a couple of minor nitpicks around initialisation of variables that almost certainly aren't critical. once they're addressed, no need for a re-review - just push the button if you're happy that it's working on the robot.

2024-03-17 10:18 UTC, robberwick commented on libs/state_estimator/src/state_estimator.cpp
> +        std::array<float, NUM_TOF_SENSORS> xList, yList;
minor: `xList` and `yList` are uninitialsed here - that's probably fine, as long as `std::array<float, NUM_TOF_SENSORS>` has more members than `xSize` (which it almost certainly does). To be defensive, it's a good idea to initialise the contents of the `xList` and `yList` arrays:
```suggestion
std::array<float, NUM_TOF_SENSORS> xList = {0.0f};
std::array<float, NUM_TOF_SENSORS> yList = {0.0f};
```

2024-03-17 10:18 UTC, robberwick commented on libs/state_estimator/include/state_estimator.h
> +        float arenaSize;
do we need this as a local property at all? can the `CONFIG::ARENA_SIZE` not be used in its place wherever it is referenced?

2024-03-17 11:38 UTC, markmellors commented
tested, working

2024-03-17 11:38 UTC, merged