Ackermann steering
thingswebuilt/osod24_firmware pull request #9
Opened 2023-12-27 16:24 UTC by markmellors

lots of changes to try to make the ackermann mixer interchangeable with the tank steer mixer, and to get the ackermann mixer working with the servos. I'm not really happy with the changes to make the ackermann mixer interchangeable with the tank mixer, but I couldn't think of a better way to do it. 
It works fine, two minor issues (that we can discuss later and/or raise issues for):
1) the steering servos twitch when stationary. there's a check in statemanager.cpp to disable the servos when that wheel isn't rotating, but wiuth my DX5e transmitter, the "neutral" stick position varies so much that it can cause the wheels to actually turn, even with hands off the stick. The current threshold is a compromise value, it can probably be reduced for an SBus transitter with better joystick pots, and set very low or eliminated entirely for autonomous code
2) because the steering has a large scrub radius (offset from steering pivot axis to wheel contact patch), a change in steering angle should be accompanied by a corresponding wheel rotation to correct for the relative motion, otherwise there are minor steering/odometry errors. 
This branch wraps up changes from a few other branches, possibly it'd be worth looking at them in isolation. The git graph should make that clear. I think its SI_units_mixer and steering_servos. there's also ackermann, but that wasn't complete enough to be worth looking at.
also, it still has the debug prints in the mixer. I can get rid of them, maybe after a merge candidate has been created?

2023-12-28 11:46 UTC, robberwick requested changes
looks good - some comments around being a bit DRYer, but otherwise looking good. there's some conflicts with main that need to be resolved before it can be merged, too.

2023-12-28 11:46 UTC, robberwick commented on libs/mixer/include/ackermann_mixer.h
> +        void setMaxSteeringAngle(float angle); //getter for turn radius
minor: copy pasta comment?

2023-12-28 11:46 UTC, robberwick commented on libs/mixer/include/mixer_strategy.h
> +    struct AckermannOutput {
might it be worth having a struct with 2 fields: `speeds` and `angles`? then each could have it's own structs with the fields `frontLeft, frontRight, rearLeft, rearRight` and `left, right`. by composing the struct in this way, we keep some logical sperattion of the two concerns, and we would have structs for describing motor speeds independent of angles if that were ever necessary.

2023-12-28 11:46 UTC, robberwick commented on libs/mixer/src/ackermann_mixer.cpp
> +}
get you with your templates - :-D

2023-12-28 11:46 UTC, robberwick commented on libs/mixer/src/ackermann_mixer.cpp
> +            // constrain steering angles
there's a lot of repeated calculations going on in this block that could be either done once and reused, both at the low level (i.e. `turnRadius +/- wheelTrack / 2` isn't going to change during the scope of the function call) or the higher level where we're calculating front left and front right speed - ideally that would be a function that takes the parameters needed, and spits out the result, so that there's no risk of copy/paste errors if we need to amend anything (i.e.we shouldn't be repeating the whole of `angularVelocity * std::sqrt((turnRadius - wheelTrack / 2) * (turnRadius - wheelTrack / 2) + wheelBase * wheelBase)` solely to change some signs, when we could define that operation once and do the right thing based on a left/right parameter)

2023-12-28 11:46 UTC, robberwick commented on libs/mixer/src/ackermann_mixer.cpp
> +            result.frontRightAngle = std::fmin(std::fmax(tempFrontRightAngle, -maxSteeringAngle), maxSteeringAngle);
`std::clamp`? https://en.cppreference.com/w/cpp/algorithm/clamp

2023-12-28 11:46 UTC, robberwick commented on libs/mixer/src/ackermann_mixer.cpp
> +            result.frontLeftSpeed = result.frontLeftSpeed * std::cos(tempFrontLeftAngle - result.frontLeftAngle);
i think I'd like to see the calculation of the angle and speed refactored out into a single function so that we can contain the use of that temp angle value. bonus points for using pointers so that we can set both things by reference in that refactored function, rather than passing values around.

2023-12-28 11:46 UTC, robberwick commented on libs/statemanager/src/statemanager.cpp
> +        if (std::fabs(ackermannOutput.frontRightSpeed) > 0.05) {
let's refactor this logic into a single function that takes the servo instance, speed and angle and does the correct thing, rather than repeating ourselves

2023-12-30 11:07 UTC, markmellors commented on libs/mixer/include/mixer_strategy.h
> +    struct AckermannOutput {
discussed and agreed we don't need to change it for now/this project.

2023-12-30 17:42 UTC, robberwick commented on libs/mixer/include/mixer_strategy.h
> +    struct AckermannOutput {
What I meant was that we should still change the struct to be `speeds` and `angles`, with their corresponding values, because that's the correct thing to do for this project (and it's a nicer way of logically organising things), but that I wouldn't worry too much about this implementation not being correct for _future_ projects, as that's a problem for Future Us, and screw those guys ;-)

2023-12-30 17:43 UTC, robberwick commented on libs/mixer/include/mixer_strategy.h
> +    struct AckermannOutput {
if you're happy for that to happen, I can make that change and do a PR against your branch. Just let me know.

2023-12-30 17:44 UTC, robberwick commented on libs/mixer/include/mixer_strategy.h
> +    struct AckermannOutput {
actually, at a minimum, we should update the comment on line 10 because that's now out of date, but I'm being super picky now.. :-)

2023-12-31 15:20 UTC, robberwick approved these changes
LGTM :+1:

2023-12-31 15:20 UTC, merged